// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALhq-Cn31vLzf5J-fGgBByBgACGMMVpU',
    appId: '1:20696203693:web:44c7fd8633491977546124',
    messagingSenderId: '20696203693',
    projectId: 'inshare-fed44',
    authDomain: 'inshare-fed44.firebaseapp.com',
    storageBucket: 'inshare-fed44.firebasestorage.app',
    measurementId: 'G-D64425KK4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF84mH6mbCanx9XdmuZ1LNerbTmXqr9oE',
    appId: '1:20696203693:android:c601997b8caa23a8546124',
    messagingSenderId: '20696203693',
    projectId: 'inshare-fed44',
    storageBucket: 'inshare-fed44.firebasestorage.app',
  );

}